FROM alpine:3.20

ARG PB_VERSION=0.30.0

RUN apk add --no-cache \
    ca-certificates \
    unzip

ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pocketbase.zip
RUN unzip /tmp/pocketbase.zip -d /pb \
    && rm /tmp/pocketbase.zip

COPY server/pb_migrations /pb/pb_migrations
COPY server/pb_hooks /pb/pb_hooks

WORKDIR /pb
EXPOSE 8090
CMD ["./pocketbase", "serve", "--http=0.0.0.0:8090"]
